import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { formatCompactDZD, formatDZD } from "@/lib/currency";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowUpRight, Banknote, BarChart3, Boxes, CircleDollarSign, FileInput, PackageCheck, ReceiptText, ShoppingBag, TrendingUp } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { useLocation } from "wouter";

const money = (value: number | string) => formatDZD(value);
const compactMoney = (value: number) => formatCompactDZD(value);
const shortDate = (value: string) => new Date(`${value}T12:00:00`).toLocaleDateString(undefined, { month: "short", day: "numeric" });

export default function Overview() {
  const { user } = useAuth();
  const { t } = useTranslation();
  const [, setLocation] = useLocation();
  const [storeFilter, setStoreFilter] = useState("all");
  const [showAllLowStock, setShowAllLowStock] = useState(false);
  const dashboard = trpc.inventory.dashboard.useQuery(undefined, { enabled: Boolean(user?.isSuperAdmin || user?.role === "super_admin") });
  const analyticsInput = useMemo(() => ({ lowStockThreshold: 5, ...(storeFilter !== "all" ? { storeId: Number(storeFilter) } : {}) }), [storeFilter]);
  const analytics = trpc.inventory.analytics.useQuery(analyticsInput, { enabled: Boolean(user?.isSuperAdmin || user?.role === "super_admin") });

  if (dashboard.isLoading || analytics.isLoading) return <div className="space-y-6"><Skeleton className="h-48 rounded-[1.75rem]" /><div className="grid gap-4 md:grid-cols-4"><Skeleton className="h-32 rounded-2xl" /><Skeleton className="h-32 rounded-2xl" /><Skeleton className="h-32 rounded-2xl" /><Skeleton className="h-32 rounded-2xl" /></div><Skeleton className="h-80 rounded-[1.5rem]" /></div>;

  const report = analytics.data;
  const selectionName = storeFilter === "all" ? t("dashboard.allBranches") : dashboard.data?.branches.find(branch => String(branch.id) === storeFilter)?.name ?? t("dashboard.branch");

  return <div className="dashboard-space space-y-6 pb-10">
    <section className="relative overflow-hidden rounded-[1.75rem] bg-[#12241e] px-6 py-7 text-white shadow-[0_20px_60px_-24px_rgba(18,36,30,.55)] sm:px-8">
      <div className="absolute -right-14 -top-24 h-64 w-64 rounded-full border-[34px] border-[#c7e661]/20" /><div className="absolute right-28 bottom-[-90px] h-48 w-48 rounded-full bg-[#e8896a]/10" />
      <div className="relative flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div className="max-w-2xl"><div className="mb-4 flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-[#c7e661]"><span className="h-2 w-2 rounded-full bg-[#c7e661]" /> {t("dashboard.eyebrow")}</div><h1 className="font-display text-3xl font-bold tracking-[-.04em] sm:text-4xl">{t("dashboard.title")}</h1><p className="mt-3 max-w-xl text-sm leading-6 text-white/70">{t("dashboard.subtitle")}</p></div><div className="flex flex-col gap-3 sm:flex-row sm:items-end"><div className="w-full sm:w-52"><p className="mb-1.5 text-xs font-semibold uppercase tracking-[.08em] text-white/55">{t("dashboard.scope")}</p><Select value={storeFilter} onValueChange={setStoreFilter}><SelectTrigger className="border-white/15 bg-white/10 text-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">{t("dashboard.allBranches")}</SelectItem>{dashboard.data?.branches.map(branch => <SelectItem key={branch.id} value={String(branch.id)}>{branch.name}</SelectItem>)}</SelectContent></Select></div><Button onClick={() => setLocation("/invoice")} className="h-10 bg-[#c7e661] text-[#12241e] hover:bg-[#d8ed86]"><FileInput className="me-2 h-4 w-4" /> {t("dashboard.addInventory")}</Button></div></div>
    </section>

    <section className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-xl font-bold text-[#12241e]">{t("dashboard.snapshot")}</h2><p className="mt-1 text-sm text-muted-foreground">{selectionName} · {t("dashboard.scopeDetail")}</p></div><Badge className="bg-[#e6f0cb] text-[#42634c] hover:bg-[#e6f0cb]"><TrendingUp className="me-1.5 h-3.5 w-3.5" /> {t("dashboard.historicalCost")}</Badge></section>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <Kpi icon={Banknote} label={t("dashboard.revenue")} value={money(report?.kpis.totalRevenue ?? 0)} detail={t("dashboard.revenueDetail")} tone="olive" />
      <Kpi icon={CircleDollarSign} label={t("dashboard.profit")} value={money(report?.kpis.netProfit ?? 0)} detail={t("dashboard.profitDetail")} tone="terracotta" />
      <Kpi icon={PackageCheck} label={t("dashboard.itemsSold")} value={(report?.kpis.totalItemsSold ?? 0).toLocaleString()} detail={t("dashboard.itemsDetail")} tone="sand" />
      <Kpi icon={ReceiptText} label={t("dashboard.transactions")} value={(report?.kpis.totalTransactions ?? 0).toLocaleString()} detail={t("dashboard.transactionsDetail")} tone="sky" />
    </section>

    <section className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
      <Card className="border-0 bg-white shadow-[0_14px_42px_-25px_rgba(18,36,30,.35)]"><CardHeader className="border-b border-[#e8ece6] px-5 py-5"><CardTitle className="flex items-center gap-2 font-display text-lg"><BarChart3 className="h-5 w-5 text-[#52745a]" /> {t("dashboard.branchPerformance")}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{t("dashboard.branchDetail")}</p></CardHeader><CardContent className="h-[310px] p-4">{report?.branchPerformance.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={report.branchPerformance} margin={{ top: 12, right: 12, left: 0, bottom: 0 }}><CartesianGrid stroke="#e8ece6" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="storeName" tick={{ fill: "#68786b", fontSize: 12 }} axisLine={false} tickLine={false} /><YAxis tickFormatter={compactMoney} tick={{ fill: "#68786b", fontSize: 11 }} axisLine={false} tickLine={false} width={64} /><Tooltip formatter={(value: number, name: string) => [money(value), name === "revenue" ? t("dashboard.revenue") : t("dashboard.profit")]} cursor={{ fill: "#f2f5ef" }} contentStyle={{ border: "1px solid #dce4d9", borderRadius: "12px", boxShadow: "0 12px 30px -20px rgba(18,36,30,.4)" }} /><Legend formatter={value => value === "revenue" ? t("dashboard.revenue") : t("dashboard.profit")} /><Bar dataKey="revenue" fill="#52745a" radius={[6, 6, 0, 0]} maxBarSize={40} /><Bar dataKey="netProfit" fill="#e8896a" radius={[6, 6, 0, 0]} maxBarSize={40} /></BarChart></ResponsiveContainer> : <ChartEmpty label={t("dashboard.noTrend")} />}</CardContent></Card>
      <Card className="border-0 bg-white shadow-[0_14px_42px_-25px_rgba(18,36,30,.35)]"><CardHeader className="border-b border-[#e8ece6] px-5 py-5"><CardTitle className="flex items-center gap-2 font-display text-lg"><TrendingUp className="h-5 w-5 text-[#52745a]" /> {t("dashboard.salesTrend")}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{t("dashboard.trendDetail")}</p></CardHeader><CardContent className="h-[310px] p-4">{report?.salesTrend.length ? <ResponsiveContainer width="100%" height="100%"><LineChart data={report.salesTrend} margin={{ top: 12, right: 12, left: -12, bottom: 0 }}><CartesianGrid stroke="#e8ece6" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="date" tickFormatter={shortDate} tick={{ fill: "#68786b", fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis allowDecimals={false} tick={{ fill: "#68786b", fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip labelFormatter={value => shortDate(String(value))} formatter={(value: number, name: string) => [value, name === "itemsSold" ? t("dashboard.itemsSold") : t("dashboard.transactions")]} contentStyle={{ border: "1px solid #dce4d9", borderRadius: "12px", boxShadow: "0 12px 30px -20px rgba(18,36,30,.4)" }} /><Legend formatter={value => value === "itemsSold" ? t("dashboard.itemsSold") : t("dashboard.transactions")} /><Line type="monotone" dataKey="itemsSold" stroke="#52745a" strokeWidth={3} dot={{ r: 3, fill: "#52745a" }} activeDot={{ r: 5 }} /><Line type="monotone" dataKey="transactions" stroke="#e8896a" strokeWidth={2} dot={{ r: 3, fill: "#e8896a" }} /></LineChart></ResponsiveContainer> : <ChartEmpty label={t("dashboard.noTrend")} />}</CardContent></Card>
    </section>

    <section className="grid gap-6 xl:grid-cols-[.85fr_1.15fr]">
      <Card className="border-0 bg-white shadow-[0_14px_42px_-25px_rgba(18,36,30,.35)]"><CardHeader className="flex flex-row items-start justify-between space-y-0 border-b border-[#e8ece6] px-5 py-4"><div><CardTitle className="flex items-center gap-2 font-display text-lg"><AlertTriangle className="h-5 w-5 text-[#b56a2d]" /> {t("dashboard.lowStock")}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{t("dashboard.lowStockDetail", { threshold: 5 })}</p></div><div className="flex items-center gap-2"><Badge className="bg-[#fff0d8] text-[#a66b28] hover:bg-[#fff0d8]">{report?.lowStock.length ?? 0}</Badge>{(report?.lowStock.length ?? 0) > 5 && <Button variant="ghost" size="sm" onClick={() => setShowAllLowStock(current => !current)} aria-expanded={showAllLowStock} className="whitespace-nowrap text-xs text-[#42634c] hover:text-[#12241e]">{showAllLowStock ? "عرض أقل" : "Show More / عرض المزيد"}</Button>}</div></CardHeader><CardContent className="p-0">{report?.lowStock.length ? showAllLowStock ? <div className="max-h-[356px] overflow-auto"><table className="w-full text-start text-sm"><thead className="sticky top-0 bg-[#fbfcfa] text-[11px] uppercase tracking-[.08em] text-muted-foreground"><tr><th className="px-5 py-3 font-medium">{t("dashboard.product")}</th><th className="px-3 py-3 font-medium">{t("dashboard.branch")}</th><th className="px-5 py-3 text-end font-medium">{t("dashboard.onHand")}</th></tr></thead><tbody>{report.lowStock.map(product => <tr key={product.id} className="border-t border-[#edf0eb]"><td className="px-5 py-3.5 font-medium text-[#24382d]">{product.name}</td><td className="px-3 py-3.5 text-xs text-muted-foreground">{product.storeName}</td><td className="px-5 py-3.5 text-end"><span className="font-mono font-semibold text-[#b56a2d]">{product.quantityOnHand}</span></td></tr>)}</tbody></table></div> : <div className="flex flex-nowrap gap-2 overflow-x-auto p-3">{report.lowStock.slice(0, 5).map(product => <div key={product.id} className="min-w-[170px] shrink-0 rounded-xl border border-[#edf0eb] bg-[#fbfcfa] px-3 py-2.5"><p className="truncate text-sm font-semibold text-[#24382d]" title={product.name}>{product.name}</p><p className="mt-1 truncate text-[11px] text-muted-foreground">{product.storeName}</p><p className="mt-1 font-mono text-xs font-semibold text-[#b56a2d]">{product.quantityOnHand} {t("dashboard.onHand")}</p></div>)}</div> : <div className="flex min-h-[160px] flex-col items-center justify-center px-6 text-center"><Boxes className="mb-3 h-8 w-8 text-[#8aa38c]" /><p className="font-medium text-[#24382d]">{t("dashboard.healthy")}</p><p className="mt-1 text-sm text-muted-foreground">{t("dashboard.healthyDetail", { threshold: 5 })}</p></div>}</CardContent></Card>
      <Card className="border-0 bg-white shadow-[0_14px_42px_-25px_rgba(18,36,30,.35)]"><CardHeader className="flex flex-row items-start justify-between space-y-0 border-b border-[#e8ece6] px-5 py-5"><div><CardTitle className="flex items-center gap-2 font-display text-lg"><ShoppingBag className="h-5 w-5 text-[#52745a]" /> {t("dashboard.transactionLedger")}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{t("dashboard.ledgerDetail")}</p></div><Button variant="ghost" className="text-xs text-[#42634c] hover:text-[#12241e]" onClick={() => setLocation("/pos")}>{t("dashboard.openPos")} <ArrowUpRight className="ms-1 h-3.5 w-3.5" /></Button></CardHeader><CardContent className="p-0">{report?.ledger.length ? <div className="max-h-[356px] overflow-auto"><table className="w-full min-w-[690px] text-start text-sm"><thead className="sticky top-0 bg-[#fbfcfa] text-[11px] uppercase tracking-[.08em] text-muted-foreground"><tr><th className="px-5 py-3 font-medium">{t("dashboard.date")}</th><th className="px-3 py-3 font-medium">{t("dashboard.branch")}</th><th className="px-3 py-3 font-medium">{t("dashboard.cashier")}</th><th className="px-3 py-3 text-end font-medium">{t("dashboard.items")}</th><th className="px-5 py-3 text-end font-medium">{t("dashboard.total")}</th></tr></thead><tbody>{report.ledger.map(sale => <tr key={sale.id} className="border-t border-[#edf0eb]"><td className="px-5 py-3.5 text-xs text-muted-foreground">{new Date(sale.createdAt).toLocaleString()}</td><td className="px-3 py-3.5 font-medium text-[#24382d]">{sale.storeName}</td><td className="px-3 py-3.5 text-muted-foreground">{sale.cashierName ?? "—"}</td><td className="px-3 py-3.5 text-end font-mono text-[#52745a]">{sale.itemCount}</td><td className="px-5 py-3.5 text-end font-mono font-semibold text-[#24382d]">{money(sale.total)}</td></tr>)}</tbody></table></div> : <div className="flex min-h-[230px] flex-col items-center justify-center px-6 text-center"><ReceiptText className="mb-3 h-8 w-8 text-[#8aa38c]" /><p className="font-medium text-[#24382d]">{t("dashboard.noSales")}</p><p className="mt-1 text-sm text-muted-foreground">{t("dashboard.noSalesDetail")}</p></div>}</CardContent></Card>
    </section>
  </div>;
}

function Kpi({ icon: Icon, label, value, detail, tone }: { icon: typeof Banknote; label: string; value: string; detail: string; tone: "olive" | "terracotta" | "sand" | "sky" }) {
  const color = { olive: "bg-[#e6f0cb] text-[#42634c]", terracotta: "bg-[#fce1d9] text-[#b85b43]", sand: "bg-[#fff0cf] text-[#a87315]", sky: "bg-[#deeff4] text-[#397687]" }[tone];
  return <Card className="border-0 bg-white shadow-[0_12px_35px_-26px_rgba(18,36,30,.3)]"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.1em] text-muted-foreground">{label}</p><p className="mt-3 font-display text-2xl font-bold tracking-[-.04em] text-[#12241e] sm:text-3xl">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${color}`}><Icon className="h-4 w-4" /></span></div></CardContent></Card>;
}

function ChartEmpty({ label }: { label: string }) { return <div className="flex h-full flex-col items-center justify-center text-center"><BarChart3 className="mb-3 h-8 w-8 text-[#8aa38c]" /><p className="max-w-xs text-sm leading-6 text-muted-foreground">{label}</p></div>; }
