export type AnalyticsStore = { id: number; name: string; type: "cosmetics" | "bookstore" | "clothing" | "gifts" | "other" };
export type AnalyticsSale = { id: number; storeId: number; storeName: string; cashierName: string | null; total: string; createdAt: Date };
export type AnalyticsSaleLine = { saleId: number; storeId: number; quantity: number; unitPrice: string; unitCost: string; unitDiscount: string };
export type AnalyticsReturnLine = { saleId: number; storeId: number; quantity: number; unitRefund: string; unitCost: string };
export type AnalyticsLowStock = { id: number; name: string; quantityOnHand: number; storeId: number; storeName: string; lastCostPrice: string };
export type AnalyticsOperatingExpense = { storeId: number; amount: string };
export type GlobalProductSaleLine = { storeId: number; storeName: string; productId: number | null; productName: string; quantity: number; unitPrice: string; unitCost: string; unitDiscount: string };
export type GlobalProductReturnLine = { storeId: number; storeName: string; productId: number; productName: string; quantity: number; unitRefund: string; unitCost: string };

const decimal = (value: string | number) => Number(value) || 0;
const round = (value: number) => Math.round((value + Number.EPSILON) * 100) / 100;

/**
 * Calculates branch reporting from immutable sales/returns cost snapshots plus
 * posted operating expenses. Supplier invoice cost remains inventory COGS; it
 * is not deducted a second time as an operational expense.
 */
export function calculateAnalytics(input: { stores: AnalyticsStore[]; sales: AnalyticsSale[]; saleLines: AnalyticsSaleLine[]; returnLines: AnalyticsReturnLine[]; lowStock: AnalyticsLowStock[]; expenses?: AnalyticsOperatingExpense[] }) {
  const revenueByStore = new Map<number, number>(); const grossProfitByStore = new Map<number, number>(); const expensesByStore = new Map<number, number>(); const itemsByStore = new Map<number, number>(); const transactionsByStore = new Map<number, number>(); const itemsBySale = new Map<number, number>();
  input.stores.forEach(store => { revenueByStore.set(store.id, 0); grossProfitByStore.set(store.id, 0); expensesByStore.set(store.id, 0); itemsByStore.set(store.id, 0); transactionsByStore.set(store.id, 0); });
  input.sales.forEach(sale => { revenueByStore.set(sale.storeId, (revenueByStore.get(sale.storeId) ?? 0) + decimal(sale.total)); transactionsByStore.set(sale.storeId, (transactionsByStore.get(sale.storeId) ?? 0) + 1); });
  input.saleLines.forEach(line => { const margin = (decimal(line.unitPrice) - decimal(line.unitDiscount) - decimal(line.unitCost)) * line.quantity; grossProfitByStore.set(line.storeId, (grossProfitByStore.get(line.storeId) ?? 0) + margin); itemsByStore.set(line.storeId, (itemsByStore.get(line.storeId) ?? 0) + line.quantity); itemsBySale.set(line.saleId, (itemsBySale.get(line.saleId) ?? 0) + line.quantity); });
  input.returnLines.forEach(line => { const returnedMargin = (decimal(line.unitRefund) - decimal(line.unitCost)) * line.quantity; revenueByStore.set(line.storeId, (revenueByStore.get(line.storeId) ?? 0) - decimal(line.unitRefund) * line.quantity); grossProfitByStore.set(line.storeId, (grossProfitByStore.get(line.storeId) ?? 0) - returnedMargin); itemsByStore.set(line.storeId, (itemsByStore.get(line.storeId) ?? 0) - line.quantity); });
  input.expenses?.forEach(expense => expensesByStore.set(expense.storeId, (expensesByStore.get(expense.storeId) ?? 0) + decimal(expense.amount)));
  const branchPerformance = input.stores.map(store => { const grossProfit = round(grossProfitByStore.get(store.id) ?? 0); const operatingExpenses = round(expensesByStore.get(store.id) ?? 0); const trueNetProfit = round(grossProfit - operatingExpenses); return { storeId: store.id, storeName: store.name, storeType: store.type, revenue: round(revenueByStore.get(store.id) ?? 0), grossProfit, operatingExpenses, trueNetProfit, /** Backwards-compatible alias for an existing chart consumer. */ netProfit: trueNetProfit, itemsSold: itemsByStore.get(store.id) ?? 0, transactions: transactionsByStore.get(store.id) ?? 0 }; });
  const trend = new Map<string, { date: string; revenue: number; itemsSold: number; transactions: number }>();
  input.sales.forEach(sale => { const date = new Date(sale.createdAt).toISOString().slice(0, 10); const day = trend.get(date) ?? { date, revenue: 0, itemsSold: 0, transactions: 0 }; day.revenue += decimal(sale.total); day.itemsSold += itemsBySale.get(sale.id) ?? 0; day.transactions += 1; trend.set(date, day); });
  const kpis = branchPerformance.reduce((summary, branch) => ({ totalRevenue: summary.totalRevenue + branch.revenue, grossProfit: summary.grossProfit + branch.grossProfit, operatingExpenses: summary.operatingExpenses + branch.operatingExpenses, trueNetProfit: summary.trueNetProfit + branch.trueNetProfit, totalItemsSold: summary.totalItemsSold + branch.itemsSold, totalTransactions: summary.totalTransactions + branch.transactions }), { totalRevenue: 0, grossProfit: 0, operatingExpenses: 0, trueNetProfit: 0, totalItemsSold: 0, totalTransactions: 0 });
  return { kpis: { ...kpis, totalRevenue: round(kpis.totalRevenue), grossProfit: round(kpis.grossProfit), operatingExpenses: round(kpis.operatingExpenses), trueNetProfit: round(kpis.trueNetProfit), /** Backwards-compatible alias for an existing dashboard consumer. */ netProfit: round(kpis.trueNetProfit) }, branchPerformance, salesTrend: Array.from(trend.values()).sort((left, right) => left.date.localeCompare(right.date)).map(day => ({ ...day, revenue: round(day.revenue) })), lowStock: input.lowStock, ledger: input.sales.slice(0, 20).map(sale => ({ ...sale, total: round(decimal(sale.total)), itemCount: itemsBySale.get(sale.id) ?? 0 })) };
}

/** Aggregates active-branch enterprise performance within one reporting window. */
export function calculateGlobalStatistics(input: { stores: AnalyticsStore[]; sales: Array<{ storeId: number; total: string }>; saleLines: GlobalProductSaleLine[]; returnLines: GlobalProductReturnLine[]; expenses?: AnalyticsOperatingExpense[] }) {
  const branches = new Map(input.stores.map(store => [store.id, { storeId: store.id, storeName: store.name, revenue: 0, grossProfit: 0, operatingExpenses: 0 }]));
  const products = new Map<string, { productId: number | null; storeId: number; storeName: string; name: string; unitsSold: number; revenue: number; netProfit: number }>();
  const productRow = (line: Pick<GlobalProductSaleLine, "productId" | "storeId" | "storeName" | "productName">) => { const key = `${line.storeId}:${line.productId ?? `custom:${line.productName.trim().toLocaleLowerCase()}`}`; const current = products.get(key) ?? { productId: line.productId, storeId: line.storeId, storeName: line.storeName, name: line.productName, unitsSold: 0, revenue: 0, netProfit: 0 }; products.set(key, current); return current; };
  input.sales.forEach(sale => { const branch = branches.get(sale.storeId); if (branch) branch.revenue += decimal(sale.total); });
  input.saleLines.forEach(line => { const revenue = (decimal(line.unitPrice) - decimal(line.unitDiscount)) * line.quantity; const profit = (decimal(line.unitPrice) - decimal(line.unitDiscount) - decimal(line.unitCost)) * line.quantity; const branch = branches.get(line.storeId); if (branch) branch.grossProfit += profit; const product = productRow(line); product.unitsSold += line.quantity; product.revenue += revenue; product.netProfit += profit; });
  input.returnLines.forEach(line => { const refund = decimal(line.unitRefund) * line.quantity; const returnedProfit = (decimal(line.unitRefund) - decimal(line.unitCost)) * line.quantity; const branch = branches.get(line.storeId); if (branch) { branch.revenue -= refund; branch.grossProfit -= returnedProfit; } const product = productRow(line); product.unitsSold -= line.quantity; product.revenue -= refund; product.netProfit -= returnedProfit; });
  input.expenses?.forEach(expense => { const branch = branches.get(expense.storeId); if (branch) branch.operatingExpenses += decimal(expense.amount); });
  const branchContributions = Array.from(branches.values()).map(branch => { const grossProfit = round(branch.grossProfit); const operatingExpenses = round(branch.operatingExpenses); const trueNetProfit = round(grossProfit - operatingExpenses); return { ...branch, revenue: round(branch.revenue), grossProfit, operatingExpenses, trueNetProfit, /** Retained to avoid breaking existing visualization field names. */ netProfit: trueNetProfit }; });
  const totalSales = round(branchContributions.reduce((sum, branch) => sum + branch.revenue, 0)); const grossProfit = round(branchContributions.reduce((sum, branch) => sum + branch.grossProfit, 0)); const operatingExpenses = round(branchContributions.reduce((sum, branch) => sum + branch.operatingExpenses, 0)); const trueNetProfit = round(branchContributions.reduce((sum, branch) => sum + branch.trueNetProfit, 0)); const positiveProfitTotal = branchContributions.reduce((sum, branch) => sum + Math.max(0, branch.trueNetProfit), 0);
  const contributions = branchContributions.map(branch => ({ ...branch, salesPercent: totalSales > 0 ? round((branch.revenue / totalSales) * 100) : 0, profitPercent: positiveProfitTotal > 0 ? round((Math.max(0, branch.trueNetProfit) / positiveProfitTotal) * 100) : 0 }));
  const rankedProducts = Array.from(products.values()).map(product => ({ ...product, revenue: round(product.revenue), netProfit: round(product.netProfit) }));
  return { kpis: { totalSales, grossProfit, operatingExpenses, trueNetProfit, /** Backwards-compatible alias for existing pages. */ totalNetProfit: trueNetProfit }, branchContributions: contributions, topBestSelling: rankedProducts.filter(product => product.unitsSold > 0).sort((left, right) => right.unitsSold - left.unitsSold || right.netProfit - left.netProfit).slice(0, 5), topMostProfitable: rankedProducts.filter(product => product.netProfit > 0).sort((left, right) => right.netProfit - left.netProfit || right.unitsSold - left.unitsSold).slice(0, 5) };
}
